apiVersion: v1
kind: ConfigMap
metadata:
  name: vidao-web
  namespace: {{ include "vidao.namespace" . }}
  labels:
    {{- include "vidao.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.web.env }}
  {{- if not (and $.Values.test.enabled (eq $k "NODE_ENV")) }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.test.enabled }}
  NODE_ENV: "test"
  TEST_AUTH_SECRET: {{ .Values.test.authSecret | quote }}
  {{- end }}
