{{- if not .Values.secrets.externalSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.secretName }}
  namespace: {{ include "vidao.namespace" . }}
  labels:
    {{- include "vidao.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.DATABASE_URL | quote }}
  PRIVY_APP_ID: {{ .Values.secrets.PRIVY_APP_ID | quote }}
  PRIVY_APP_SECRET: {{ .Values.secrets.PRIVY_APP_SECRET | quote }}
  TRANSAK_ACCESS_TOKEN: {{ .Values.secrets.TRANSAK_ACCESS_TOKEN | quote }}
  CRON_SECRET: {{ .Values.secrets.CRON_SECRET | quote }}
  DEPLOYER_PRIVATE_KEY: {{ .Values.secrets.DEPLOYER_PRIVATE_KEY | quote }}
{{- end }}
