apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vidao-web-data
  namespace: {{ include "vidao.namespace" . }}
  labels:
    {{- include "vidao.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: {{ .Values.web.storage.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.web.storage.size }}
