apiVersion: v1
kind: ServiceAccount
metadata:
  name: vidao-chainpool
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vidao-chainpool
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps"]
    verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
  - apiGroups: [""]
    resources: ["pods/log", "pods/status"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vidao-chainpool
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: vidao-chainpool
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: vidao-chainpool
  apiGroup: rbac.authorization.k8s.io
